# -*- coding: utf-8 -*-
"""DSPL IND-SUIC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1G20W0bBnhOCIKMekj3ZcB0ZLpiQz_l
"""

import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/DSPL IND/WB_WDI_SH_STA_SUIC_FE_P5.csv')
df2 = pd.read_csv('/content/drive/MyDrive/DSPL IND/WB_WDI_SH_STA_SUIC_MA_P5.csv')
df3 = pd.read_csv('/content/drive/MyDrive/DSPL IND/WB_WDI_SH_STA_SUIC_P5 (1).csv')

print(df.head())
print(df2.head())
print(df3.head())

print(df.columns)

combined_df = pd.concat([df, df2], ignore_index=True)

print(combined_df.shape)
print(combined_df['SEX'].value_counts())

final_df = pd.concat([combined_df, df3], ignore_index=True)

print(final_df.shape)
print(final_df['SEX'].value_counts())

df1= final_df

df1.head()

df1 = df1.drop(columns=df1.loc[:, 'COMP_BREAKDOWN_1_LABEL':'OBS_CONF_LABEL'].columns)

df1 = df1.drop(columns=df1.loc[:, 'AGG_METHOD':'FREQ_LABEL'].columns)

df1 = df1.drop(columns=['URBANISATION_LABEL'])

df1 = df1.drop(columns=df1.loc[:, 'AGE':'COMP_BREAKDOWN_3'].columns)

remove_labels = [
    "IBRD only", "IDA & IBRD total",
    "IDA blend", "IDA only", "IDA total",
    "Early-demographic dividend",
    "Late-demographic dividend", "Post-demographic dividend", "Pre-demographic dividend",
    "Fragile and conflict affected situations", "Heavily indebted poor countries (HIPC)",
    "Least developed countries: UN classification", "OECD members", "Small states",
    "Other small states", "Pacific island small states", "Caribbean small states",
    "East Asia & Pacific (IDA & IBRD)", "Europe & Central Asia (IDA & IBRD)",
    "Latin America & Caribbean (IDA & IBRD)",
    "Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)",
    "South Asia (IDA & IBRD)", "Sub-Saharan Africa (IDA & IBRD)",
    "East Asia & Pacific (excluding high income)",
    "Europe & Central Asia (excluding high income)",
    "Latin America & Caribbean (excluding high income)",
    "Middle East, North Africa, Afghanistan & Pakistan (excluding high income)",
    "Sub-Saharan Africa (excluding high income)",
]

df1 = df1[~df1['REF_AREA_LABEL'].isin(remove_labels)]

print(df1.shape)
print(df1['SEX'].value_counts())

"""**1,848 rows** were removed from the original **15,378 records**. These rows were World Bank aggregate
classifications (e.g. lending categories) that were derived from individual country data.
Keeping them would cause double-counting and skew the analysis. The cleaned dataset contains **13,530 rows**.
"""

df1.to_csv('/content/drive/MyDrive/DSPL IND/Final_WB_WDI_SH_STA_SUIC_.csv', index=False)

